### ISSUE TITLE
A.T for applying to a job

### ISSUE THREAD

**Issue by marinaGirgis** [Irisvella/DreamTeam-SOEN-341-Project-2023#45]
1. Employees must sign up for an account to be able to further login.
2. Employees must input their personal information and upload their C.V. 
3. Employees must log in to their accounts once created.
4. Employees must search their job titles in the nav bar.
5. Employees must select the jobs that best match their profile.
6. Employees must click on apply now to apply for the selected job.

**Comment by Fatoumatabintabarry** [comment]
#45 completed
