### ISSUE TITLE
UX Light and Dark Theme Change 

### ISSUE THREAD

**Issue by Onestarsin** [Irisvella/DreamTeam-SOEN-341-Project-2023#50]
As a User, I want to be able to switch the UX themes between light and dark modes with the click of a button, so that I can customize the readability depending on light conditions.

Task description:

- Create a button in the dropdown menu or on the nav bar
- Create the necessary function to toggle between the two themes 
- Add an eventlistener, so that when the button is  clicked it calls the function

**Comment by Fatoumatabintabarry** [comment]
#50 task completed in my previous commit
