### ISSUE TITLE
AT 4.1 : for UX change

### ISSUE THREAD

**Issue by Onestarsin** [Irisvella/DreamTeam-SOEN-341-Project-2023#51]
This acceptance test is for #50 

User acceptance flow

1. Verify that for all users, the theme is set to light mode
2. Users can click the button to change the theme from light to dark and vice versa
3. Verify the transition for all the different pages
4. Reload, log out, log in, and repeat step 3 for each.

**Comment by Fatoumatabintabarry** [comment]
#50 partially completed in previous commit
