### ISSUE TITLE
AT for dark mode

### ISSUE THREAD

**Issue by marinaGirgis** [Irisvella/DreamTeam-SOEN-341-Project-2023#57]
1. The user must log in to their account with their sign-up information.
2. The user must click on the dropdown menu or on the nav bar to have access to the dark mode option.
3. The user must click on the dark mode icon to switch between the two themes.
4. The user must click on the icon again to switch back to the default light mode.

**Comment by Fatoumatabintabarry** [comment]
#57 is completed

**Comment by Fatoumatabintabarry** [comment]
#57 partially completed for homepage
