### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by Fatoumatabintabarry** [Irisvella/DreamTeam-SOEN-341-Project-2023#6]
On the job search homepage, I should be able to use the search bar to filter job listings based on keywords, location, and job category. The job listings should include important information such as the job title, company name, location, and brief job description.
 I should be able to easily create a profile on the job search homepage, so I can save my information and easily apply for jobs. There should be a prominent "Sign Up" or "Create Profile" button, which will take me to a page form where I can input my information, such as my resume and cover letter.

By having these features, I can have a smooth and efficient job search experience, easily find job opportunities that match my criteria, and quickly apply for jobs that interest me.
Task breakdown: 
- Create a nav bar , with a drowpdown menu , log in and signup button
- Create main header section with job search bar: Allow users to search for job opportunities based on keywords, location, and job category.
-  create a section for compagny culture. 
- Create a Job listings preview section : Display job listings with clear job titles, company names, locations, and brief job descriptions.
- Footer link for socials , FAQ , support and more to TBD
Team member responsibility: Fatoumata

**Comment by Irisvella** [comment]
Story points: 5

**Comment by Fatoumatabintabarry** [comment]
As a visitor of the website , I want to be able to see the nav bar and a call to action to sign up ,( as an employer or as a candidate ) . I want to be able to see compagny culture and  the advantages for each party by signing up . I want to be redirected to the appropriate pages while clicking any menu option . I want to be able to see a preview of the job listings . I want to have an intuitive and seemless expereince . 

Task breakdown:

Create a nav bar , with a drowpdown menu , log in and signup button
create a section for compagny culture.
Create a Job listings preview section : Display job listings with clear job titles, company names, locations, and brief job descriptions.
Footer link for socials , FAQ , support and more to TBD
Team member responsibility: Fatoumata
